### ISSUE TITLE
Potential: Clickable breadcrumbs

### ISSUE THREAD

**Issue by ViktorKatz** [ViktorKatz/wdcookbook#15]
Nije neophodno, ali je kul.

**Comment by gavantee** [comment]
mislim da je njihova poenta da moš da ih klikneš

**Comment by gavantee** [comment]
oćeš da ja ovo uradim preko <v-breadcrums> ?

**Comment by gavantee** [comment]
preko b-breadcrumbs

**Comment by ViktorKatz** [comment]
To može da jede govna.
