### ISSUE TITLE
Moji komentari i ocene

### ISSUE THREAD

**Issue by ViktorKatz** [ViktorKatz/wdcookbook#18]
Debilno, ali moraju se videti na 'Moj nalog' svi komentari i sve ocene korisnika.
Predviđam komponente za komentar i ocenu...

**Comment by ViktorKatz** [comment]
Jedno ok rešenje mi se čini da je da ovde umesto vaši recepti imamo 3 dugmića: recepti, komentari i ocene
![image](https://user-images.githubusercontent.com/11558928/123333432-08f89a00-d542-11eb-8a43-bc822be408f8.png)

**Comment by gavantee** [comment]
Aj napravi dugmiće i prostor predvđen za to a ja ću ih dodati

**Comment by gavantee** [comment]
nvm ja ću

**Comment by gavantee** [comment]
gotovo
