### ISSUE TITLE
U dodaj recept snimak i slika

### ISSUE THREAD

**Issue by ViktorKatz** [ViktorKatz/wdcookbook#40]
Valjalo bi dodati mogućnost dodavanja slika i snimaka pri dodavanju recepta.
@gavantee Je l ti ovo zvuči izvodljivo?

**Comment by gavantee** [comment]
bolje na stranici recepta pošto može bilo ko
za slike sam već uradio

**Comment by gavantee** [comment]
za video ću zapravo da stavim da može samo kreator videa i to ako vide ne postoji da stoji umesto videa,
a ostalima već piše nešto tipa nema video
