### ISSUE TITLE
Progress bar težine recepta bi mogao da menja boje u zavisnosti od težine

### ISSUE THREAD

**Issue by ViktorKatz** [ViktorKatz/wdcookbook#9]
U komponenti kartice

E baki, progress bar težine recepta bi mogao da menja boje u zavisnosti od težine... Ali to možemo i posle...

_Originally posted by @ViktorKatz in https://github.com/ViktorKatz/wdcookbook/issues/8#issuecomment-867513127_

**Comment by gavantee** [comment]
reci koje boje oš i dodaću

**Comment by ViktorKatz** [comment]
Pa ono, za 1-2 zeleno, 3-4 žuto i 5 crveno. Mislim da možeš da koristiš ugrađenne varijante success, warning i danger... 
Al ovo nije ni n od neophodno.
